In [13]:
# This cell just imports necessary modules

import numpy as np

from sympy import pprint

# Matrices linear algebra

## Defining a matrix

Lecture 4, slide 3

Define matrices using numpy.matrix, and find their dimensions using numpy.shape

In [14]:
# mA is a SQUARE matrix
mA = np.matrix([[2, 3, -4],
                   [3, -1, 2],
                   [4, 2, 2]])   
# mB is a NON-SQUARE matrix
mB = np.matrix([[2, -4, 1, -2],
                   [7, 8, 0, 3]])   
                  
# REMEMBER: when stating the dimension of a matrix (e.g. 3 x 3, 2 x 4, etc)
# it's *R*ows Fi*R*st, *C*olumns Se*C*ond.
# So, mA is 3 x 3 matrix, mB is a 2 x 4 matrix.

print("The dimension of A is ", np.shape(mA)) 

print("The dimension of B is ", np.shape(mB)) 

The dimension of A is  (3, 3)
The dimension of B is  (2, 4)


## Matrix-scalar multiplication

Lecture 4, slide 5

In [15]:
mD = np.matrix([[2, -4, 1, -2],
                   [7, 8, 0, 3]])  

    
print("3*D =")
pprint(3*mD)

3*D =
 [[  6 -12   3  -6]
 [ 21  24   0   9]]


## Matrix addition and subtraction

Lecture 4, slide 6, 7

In [16]:
mE = np.matrix([[2, -4],
                   [7, 8]])
                  
mF = np.matrix([[4, 0],
                   [2, -1]])

    
print("E + F =") 
pprint(mE + mF) 

print("E - F =") 
pprint(mE - mF) 

E + F =
 [[ 6 -4]
 [ 9  7]]
E - F =
 [[-2 -4]
 [ 5  9]]


```{note}
The two matrices must have the same dimension. If they do not, Python will give ValueError. 

For example when adding mE (2 x 2) and mB (2 x 4): 
```

In [17]:
pprint(mE + mB)

ValueError: operands could not be broadcast together with shapes (2,2) (2,4) 

## Matrix-matrix multiplication

Lecture 4, slide 10

In [18]:
mE = np.matrix([[2, -4],
                   [7, 8],
                   [3, 2]])  
mH = np.matrix([[4, 0, 0, 1],
                   [2, -1, 3, -2]])                  

print("E*H =") 
pprint(mE*mH) 

E*H =
 [[  0   4 -12  10]
  [ 44  -8  24  -9]
 [ 16  -2   6  -1]]


## Matrix transpose

Lecture 4, slide 12, 13

Finding the transpose of a matrix using numpy.transpose

In [19]:
# Non-square matrix
mB = np.matrix([[2, -4],
                   [7, 8],
                   [3, 2]])
                  
mB_transpose = np.transpose(mB)
print("The transpose of (non-square) B =") 
pprint(mB_transpose) 

# Square matrix
mB = np.matrix([[2, 3, -4],
                   [3, -1, 2],
                   [4, 2, 2]])                 

mB_transpose = np.transpose(mB)
print("The transpose of (square) B =") 
pprint(mB_transpose) 

The transpose of (non-square) B =
[[ 2  7  3] 
 [-4  8  2]]
The transpose of (square) B =
[[ 2  3  4] 
 [ 3 -1  2] 
 [-4  2  2]]


## Identity matrix

Lecture 4, slide 15

Create identity matrix using numpy.identity

In [20]:
mI = np.identity(3)

print("I=")
pprint(mI)

mB = np.matrix([[2, 3, -4],
                   [3, -1, 2],
                   [4, 2, 2]])                 


mIB = mI*mB
print("I*B =")
pprint(mIB)

# mIB should be equal to mB
if np.allclose(mB, mIB) == True:
    print("B = I*B")
else:
    print("Error")

I=
[[1. 0. 0.] 
 [0. 1. 0.] 
 [0. 0. 1.]]
I*B =
 [[ 2.  3. -4.]
  [ 3. -1.  2.]
 [ 4.  2.  2.]]
B = I*B


## Determinants

Lecture 4, slide 16

Finding determinants of matrices using numpy.linalg.deg

In [21]:
# 2 x 2 example
mD = np.matrix([[1, 4],
                   [-3, 5]])            
sDet = np.linalg.det(mD)
print("det(D) = %.2f" % sDet) 

# 3 x 3 example
mA = np.matrix([[1, 2, 4],
                   [-3, 1, -2],
                   [3, 2, 5]])   
det = np.linalg.det(mA)
print("det(A) = %.2f" % sDet) 

det(D) = 17.00
det(A) = 17.00


## Solving systems of linear equations 

Finding solutions to linear equations using numpy.linalg.solve

In [22]:
# Set up a system of the form Ax = b
mA = np.matrix([[2, 3, -4],
                   [3, -1, 2],
                   [4, 2, 2]])               
vb = np.array([10, 3, 8])

# Solve the system of linear equations
vX = np.linalg.solve(mA, vb)

print("The solution to Ax = b is:") 
pprint(vX) 

The solution to Ax = b is:
[ 1.86956522  1.04347826 -0.7826087 ]


## Existence of solutions

In [23]:
# Compute the determinant of the square matrix A
sDet = np.linalg.det(mA)
print("Determinant of A = %.3f" % sDet) 
if(sDet != 0):
    print("The system Ax = b has a UNIQUE solution.") 
else:
    print("The system Ax = b has either infinite solutions or no solutions.") 

Determinant of A = -46.000
The system Ax = b has a UNIQUE solution.


## Inverse of a matrix

Computing the inverse of a matrix using numpy.linalg.inv

In [24]:
# Compute the inverse of A
mA_inv = np.linalg.inv(mA)
print("The inverse of A is:") 
pprint(mA_inv) 


# Check that A*A_inv gives the identity matrix I
# NOTE: You may find that some elements of the matrix
# are around 1e-16 (i.e. 10**(-16)) instead of exactly zero.
print("A*A_inv=") 
pprint(mA*mA_inv) 

mI = np.identity(3)

if np.allclose(mI, mA*mA_inv) == True:
    print("A*A_inv gives the identity matrix")
else:
    print("Error")

The inverse of A is:
 [[ 0.13043478  0.30434783 -0.04347826]
  [-0.04347826 -0.43478261  0.34782609]
 [-0.2173913  -0.17391304  0.23913043]]
A*A_inv=
 [[ 1.00000000e+00  1.11022302e-16 -2.22044605e-16]
  [ 5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [ 5.55111512e-17  5.55111512e-17  1.00000000e+00]]
A*A_inv gives the identity matrix


```{note}
A is an object with a set of methods (you'll learn more about these in the Programming for Geoscientists course). 

Therefore, you could also use the method getI() to compute the inverse by typing A.getI()
```